### ISSUE TITLE
🚀 [Feature]: Add OpenVino / OpenVino Model Server 

### ISSUE THREAD

**Issue by jsapede** [serge-chat/serge#1017]
### Feature Description

Openvino offers hardware capabilities, even for older CPU (> Gen6). They provide framework for using models with this technology.

https://github.com/openvinotoolkit/model_server/blob/main/demos/python_demos/llm_text_generation/README.md

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@jsapede Thanks, but we already have a models server that covers Serge use-case.
