### ISSUE TITLE
🚀 [Feature]: Add LINCE-Mistal model

### ISSUE THREAD

**Issue by sergarb1** [serge-chat/serge#1021]
### Feature Description

🚀 [Feature]: Add LINCE-Mistal model https://huggingface.co/clibrain/lince-mistral-7b-it-es

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@sergarb1 You can add the model yourself by downloading the GGUF version, the copy the file to the WEIGHTS folder. Rename the extension to `.bin`.

You have to find a `GGUF` version first.

Given this model is language specific it doesnt make sense to add to the base list of Serge for now. In the future we plan on adding a URL field on Serge that will allow you to use any model directly from the UI.
