### ISSUE TITLE
have a separate page which displays downloaded moddles.

### ISSUE THREAD

**Issue by mhussaincov94** [serge-chat/serge#1065]
currently, we have a single page which displayes all moddles.
it would be useful if there was a seperate page or what have you which would only display installed/present moddles.
and a page for moddles that could be downloaded and which are not present on the system.
due to using assistive tech orca the screen reader on linux, I am unable to tell when a moddle is installed or can be downloaded.
a butten is presented by the moddle name after it's filesize is displayed, but with it not being labled I dare not press it.
this sollution if added would bypass this issue, and make things simpler for non assistive tech users as a hole.
I understand that you are very bizy, and am greatful for this lovely UI and the tytanic amounts of work which goes in to it's development.
if you doo get time, I would be greatful if this could be considdered?
thank you.
:)

**Comment by gaby** [comment]
Hello, this would make the UI more complicated than it needs to be. Ideally we just add the labels to every component and go from there.

I'm closing this sincr there's already a ticket for adding the labels to the ui components.
