### ISSUE TITLE
the ability to run gguf moddles?

### ISSUE THREAD

**Issue by mhussaincov94** [serge-chat/serge#1114]
would it be possible to add support to run gguf moddles like this?
https://huggingface.co/TheBloke/Kunoichi-7B-GGUF
I have been testing, and simply changeing the file extention from .gguf to .bin loads it ok.
but having support for the .gguf extention would help.
image I am using:
ghcr.io/serge-chat/serge:main
debian unstable with all updates installed.
docker docker compose installed and up-to-date.
using chromium from the debian repo.
thank you for considdering my request.

**Comment by gaby** [comment]
That works already the `.bin` is just how we rename the files. Serge supports GGUF.

**Comment by mhussaincov94** [comment]
hi,
they don't work.
if added with the file extention .gguf
I have just tested by adding the moddle to the default moddles directory, restarting the container and it is not showing up.

**Comment by gaby** [comment]
You have to add them with .bin, else they wont get loaded into the UI.

**Comment by gaby** [comment]
😆 That bot needs a lot work
