### ISSUE TITLE
🚀 [Feature]: add eagle 7b

### ISSUE THREAD

**Issue by osnapitsjoey** [serge-chat/serge#1121]
### Feature Description

https://huggingface.co/spaces/BlinkDL/RWKV-Gradio-2

It seems unique enough to get added.

### Additional Context (optional)

Also, is there any documentation I'm not seeing on how to get non added models working? Whenever I try to run a wizard-uncensored model or anything else I downloaded it never responds and fails in the logs

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@osnapitsjoey Not sure what the request is here?

**Comment by osnapitsjoey** [comment]
I thought the requests were for new models. Eagle 7b was what I was
requesting, and then below that I was asking if there were any docs to get
Lora models to fun that you haven't added yet as dropping the file in
weights doesn't work for me

**Comment by gaby** [comment]
Rename the file with a `.bin` extension. Lora models won't work.
