### ISSUE TITLE
🚀 [Feature]: Add Nous-Hermes-2-Mistral-7B-DPO

### ISSUE THREAD

**Issue by CevreMuhendisi** [serge-chat/serge#1155]
### Feature Description

Can you also add this model? "Nous-Hermes-2-Mistral-7B-DPO"

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@Smartappli You are the models expert here :-) Is there a GGUF for this one?

**Comment by Smartappli** [comment]
@gaby i take a look

**Comment by Smartappli** [comment]
@gaby  PR in 30 minutes

**Comment by Smartappli** [comment]
https://github.com/serge-chat/serge/pull/1156

**Comment by Smartappli** [comment]
ping @gaby

**Comment by gaby** [comment]
@CevreMuhendisi Model is now available by using `ghcr.io/serge-chat/serge:main`. The `latest` tag will have it in the next release.
