### ISSUE TITLE
Any way to make it multi-session without loading multiple models?

### ISSUE THREAD

**Issue by manageseverin** [serge-chat/serge#116]
If I access it through the web interface and other people are accessing at the same time it would mirror the answers to all the users, right ? I guess, there is no way it would differentiate between users, as it loads a single model in memory.

**Comment by gaby** [comment]
@manageseverin Correct, right now it's single user. It would need significant work to add multi-user support, or maybe we can get away with sessions.

**Comment by gaby** [comment]
Related to #950
