### ISSUE TITLE
🚀 [Feature]: add characters

### ISSUE THREAD

**Issue by redfang790** [serge-chat/serge#1185]
### Feature Description

Can you allow it so we can upload characters by Json files so we can have are own custom ai to talk to and maybe upload a chat to from other platforms

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@redfang790 What do you mean by characters? Like uploading your own data?

**Comment by gaby** [comment]
If you have the LLM model file in .gguf format, yes you can use it else it won't work. We rely on huggingface api to do stuff

**Comment by gaby** [comment]
@redfang790 LLM's are either .gguf, .bin, or some other binary format. Files are usually at least 1GB or more in size
