### ISSUE TITLE
🚀 [Feature]: Please add Gorilla: Large Language Model Connected with Massive APIs

### ISSUE THREAD

**Issue by kfowlks** [serge-chat/serge#1192]
### Feature Description

Please add the gorilla model to the default models.json. I was able to find a gguf version of the model on huggingface.co. 

https://huggingface.co/gorilla-llm/gorilla-falcon-7b-hf-v0-gguf

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@kfowlks Send a Pull Request, I will merge it

**Comment by kfowlks** [comment]
Sounds good!

**Comment by gaby** [comment]
@kfowlks For now this will be available by using `ghcr.io/serge-chat/serge:main`. Once I do a new Serge release it will be available via `ghcr.io/serge-chat/serge:latest`
