### ISSUE TITLE
llama-retrieval-plugin support?

### ISSUE THREAD

**Issue by loss-and-quick** [serge-chat/serge#125]
It will be great,if **serge** will have support  to this [`plugin`](https://github.com/lastmile-ai/llama-retrieval-plugin)

**Comment by fishscene** [comment]
Does it require a token or integration with other AI services? If so, it augments, but builds a dependency that isn’t self-hosted. I’d advocate for this if say, it enabled Serge Llama to run a query on a search-engine without having to first pipe the query through Bard/ChatGPT/etc..

**Comment by gaby** [comment]
Plugin project seems abandoned, and we are using llama-cpp-python now.
