### ISSUE TITLE
🚀 [Feature]: Add meta-llama/Meta-Llama-3-70B-Instruct

### ISSUE THREAD

**Issue by CevreMuhendisi** [serge-chat/serge#1250]
### Feature Description

Can you also add this model? "meta-llama/Meta-Llama-3-70B-Instruct"

https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@CevreMuhendisi Do they have a 7B version too? Not many people can run a 70B model

**Comment by gaby** [comment]
@CevreMuhendisi Model will show up by using the "main" tag instead of "latest".

`docker pull ghcr.io/serge-char/serge:main`

**Comment by damian-w** [comment]
I'm seeing `Failed to install llama-cpp-python` in a new Docker install - fails to start on `:main`?

**Comment by Smartappli** [comment]
https://github.com/serge-chat/serge/pull/1263
