### ISSUE TITLE
🐛 [Bug]: Can't use pre-existing model at /weights

### ISSUE THREAD

**Issue by K3rlit0** [serge-chat/serge#1272]
### Bug description

The weights directory in the docker has the ggml-model-Q4_0.gguf which is a Llama-7B-chat but it is not detected in the UI should I name it a specific name?

### Steps to reproduce

# pwd
/usr/src/app/weights
# ls
gml-model-Q4_0.gguf
# 

### Environment Information

docker on mac

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@K3rlit0 Yes, file extension is `.bin`. Just rename it to `ggml-model-Q4_0.bin`
