### ISSUE TITLE
[FEATURE] Support for custom links

### ISSUE THREAD

**Issue by Stetsed** [serge-chat/serge#130]
Good evening,

A problem I see appearing for the project is that adding new models becomes kinda tedious. So I propose instead of constantly adding more models to just add a "Download" section. You just enter a direct download link to the non-compressed files and it will automatically add them to the folder.

**Comment by gaby** [comment]
👍🏻 For adding this. May be worth also adding support for HTTP/HTTPS proxy while we are at it. @nsarrazin

**Comment by mzeng1417** [comment]
Maybe while your add it, it would be possible to implement something like a source repository with the links?

Like, make the app fetch a request to a repository that has labels [Alpaca 13B, https://some_url ], [some_other_model, some_other_url], and get the URL of the place it needs to download from, and then download it from that URL.  It would allow for easy adding of custom models into the repository.

**Comment by fishscene** [comment]
This is a neat idea. 
*dreaming a bit*:
We could have a repo list with officially "supported" models included with a default repo. But allow for folks to add their own repo's with their own lists and even remove the default repo if they don't want it.

...maybe have a disclaimer though that the project only supports the default repo's and have a button to restore the default repo so we don't get extra tickets asking for the default repo. :)

**Comment by fishscene** [comment]
> 👍🏻 For adding this. May be worth also adding support for HTTP/HTTPS proxy and custom CA while we are at it. @nsarrazin

I’ve seen other projects do this and it creates a lot of complications for folks already running their own reverse proxy/Cert issuer. 

If this does gain traction, recommend creating a flag that disables/enables it. Allows folks with their own infrastructure to easily add this in.

**Comment by gaby** [comment]
This is now supported in tag `0.3.0` :-)

**Comment by gaby** [comment]
Example models JSON file: https://github.com/serge-chat/serge/blob/main/api/src/serge/data/models.json
