### ISSUE TITLE
Allow to clear/restart the current session

### ISSUE THREAD

**Issue by Konata390** [serge-chat/serge#135]
Sometimes I like to tweak the model parameters a bit and ask a few one-off questions, but it's annoying to constantly adjust parameters, delete, adjust parameters again, etc. It would be nice to have a button that clears the current history to allow giving a new prompt without prior data muddling the results.

**Comment by snxraven** [comment]
@Konata390 Thank you for the wonderful idea! I have created #136 to complete this request.

**Comment by Konata390** [comment]
I just tested the new commit and seems to work fine. Is it be possible to add a checkbox somewhere to automatically delete the old chat after creating the new one? Right now it's 2 extra clicks every time, and it would be great to be able to skip that.
