### ISSUE TITLE
Error 500 while trying to download a model

### ISSUE THREAD

**Issue by xswirelab** [serge-chat/serge#157]
### Bug description

<img width="705" alt="image" src="https://user-images.githubusercontent.com/98958488/231694187-a7af64fa-f61b-48e3-8418-8be7b4a21bfb.png">

After running:

`docker run -d -v weights:/usr/src/app/weights -v datadb:/data/db/ -p 8008:8008 ghcr.io/nsarrazin/serge:latest`

I load `localhost:8008` and click to download a model. 

All show a error 500 in chrome's developer console.

### Steps to reproduce

1. Run container by following the instructions in the readme `docker run -d -v weights:/usr/src/app/weights -v datadb:/data/db/ -p 8008:8008 ghcr.io/nsarrazin/serge:latest`
2. Go to `localhost:8008`
3. Try and download a model
4. check chrome devtools's console tab to find the error 500

### Environment Information

Docker version: podman version 4.4.1
OS: Mac OS Monterey 12.6
CPU: 2,6 GHz 6-Core Intel Core i7
RAM: 16 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB

### Screenshots

<img width="1744" alt="image" src="https://user-images.githubusercontent.com/98958488/231695507-d6485239-ad6a-44d4-82a2-47b9214157ea.png">

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by julian70400** [comment]
Same here.
Environnement : debian 11, VM, 4 vCPUs, 16gb ram.

**Comment by bcarroll** [comment]
Did you create the directories for the volumes?
`mkdir -p weights datadb`
