### ISSUE TITLE
Unable to pull image from ghcr.io/nsarrazin/serge

### ISSUE THREAD

**Issue by gregorysandul** [serge-chat/serge#158]
Hello, 
While pulling image I have the following error.

[root@localhost ~]# docker pull ghcr.io/nsarrazin/serge:latest
Trying to pull repository ghcr.io/nsarrazin/serge ... 
Pulling repository ghcr.io/nsarrazin/serge
Error: image nsarrazin/serge:latest not found

Please advice.

**Comment by gaby** [comment]
@gregorysandul 

```bash
docker pull ghcr.io/nsarrazin/serge:latest
```

Are you behind a proxy/firewall?

**Comment by eskiiom** [comment]
Hello,

i've just tried now and I have the same issue.
I don't know if it's ghcr.io who has an issue or the image itself, but it says 

No such image: ghcr.io/nsarrazin/serge:latest | 2
-- | --

**Comment by nsarrazin** [comment]
Can you try removing your GHCR credentials ?

`docker logout ghcr.io`

then try again.

`docker pull ghcr.io/nsarrazin/serge:latest`

**Comment by gregorysandul** [comment]
[root@localhost ~]# docker logout ghcr.io
Not logged in to ghcr.io

[root@localhost ~]# docker pull ghcr.io/nsarrazin/serge:latest
Trying to pull repository ghcr.io/nsarrazin/serge ... 
Pulling repository ghcr.io/nsarrazin/serge
Error: image nsarrazin/serge:latest not found

Should I have any  GHCR credentials?

**Comment by nsarrazin** [comment]
You shouldn't but it can be an issue sometimes, I guess not this time :stuck_out_tongue:

**Comment by eskiiom** [comment]
in my case it is strange, i couldn't download it from portainer, but it worked in cli
i could then start it in portainer ...

**Comment by gaby** [comment]
@gregorysandul @nsarrazin @eskiiom Turns out that portainer hardcodes the `docker.io` registry. You have to add `gchr.io` as a custom registry.

Add it as a custom registry with auth disable:
https://docs.portainer.io/admin/registries/add/custom

**Comment by gregorysandul** [comment]
@gaby The issue is not related to portainer. In any case, added gchr.io as custom registry in my portainer install, pulled image from gchr.io, in few seconds appeared message "OK imaged was pulled" but no image appeared  in WEB interface. 
Also 
#docker images 
command on host with portainer installed shows other, but not this particular image.

Also generated access token and authenticated on  gchr.io
[root@localhost ~]# docker login ghcr.io -u gregorysandul -p github_pat_ZZZ_YYY........
Login Succeeded
[root@localhost ~]# docker pull ghcr.io/nsarrazin/serge:latest
Trying to pull repository ghcr.io/nsarrazin/serge ... 
Pulling repository ghcr.io/nsarrazin/serge
Error: image nsarrazin/serge:latest not found
[root@localhost ~]# docker logout ghcr.io
Removing login credentials for ghcr.io
[root@localhost ~]# docker pull ghcr.io/nsarrazin/serge:latest
Trying to pull repository ghcr.io/nsarrazin/serge ... 
Pulling repository ghcr.io/nsarrazin/serge
Error: image nsarrazin/serge:latest not found

Also used my username and access token in portainer settings for gchr.io, the same result - no success.

**Comment by gaby** [comment]
@gregorysandul You dont need username/password to download from ghcr.io, that must be tripping dockerd. Sounds like something it messed up with your host/portainer. I just went into my Pi, and downloaded the image.

![Screenshot_20230414-090151](https://user-images.githubusercontent.com/835733/232050921-56c99869-870d-4338-a207-d40501fadb71.png)

**Comment by gregorysandul** [comment]
I'm trying to upload it from 4 different locations, the same result.
![screen](https://user-images.githubusercontent.com/130670003/232054480-83a04e13-bfb5-4a2e-bcae-6ecdce96531f.png)

Well,  "The Mathix" does not allow me to use it :)

**Comment by gaby** [comment]
@gregorysandul still unable to pull the latest image?

**Comment by gregorysandul** [comment]
@gaby yes, still unable.
