### ISSUE TITLE
Model loads ram when chat is started, but unloads ram when response is requested

### ISSUE THREAD

**Issue by bradcrossen** [serge-chat/serge#213]
### Bug description

When a new chat is started, the model is loaded into RAM (about 8 GBs as I am using the 13B model) and everything seems fine. I request a response with a query then the RAM usage goes to about 500MB and it takes about 5 minutes for the model to start a response. Then I get about 1 token/s until the response is complete. Then the RAM usage goes back up to normal. I assume that this is not normal behavior.

### Steps to reproduce

1. Start chat.
2. Send request.
3. Watch metrics.

### Environment Information

Docker version 20.10.18, build b40c2f6
Linux
Unraid
CPU: Intel i5-4670K
RAM: 32GB

### Relevant log output

```shell
2023-04-23 23:44:34.536 | DEBUG    | serge.routers.chat:stream_ask_a_question:162 - creating Llama client
2023-04-23T23:44:34.536972-0500 DEBUG creating Llama client
llama.cpp: loading model from /usr/src/app/weights/13B.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
llama_init_from_file: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
Is this still happening? @bradcrossen using latest tag from this week

**Comment by ethdig** [comment]
> 
what is the latest status? Can you try the performance with 32gb ram?

**Comment by vanlueckn** [comment]
I have the same issue

**Comment by bearlike** [comment]
Why is this issue close? The issue still appears to still exist.
