### ISSUE TITLE
Add support for saving/loading profiles

### ISSUE THREAD

**Issue by agronholm** [serge-chat/serge#214]
I like having different settings for story writing, chatting and other use cases. In particular, I like having different initial prompts set for these use cases, and they're often accompanied with different settings for temperature and others. It would be very useful to be able to adjust your settings and then save them to a profile, and later pick which profile you want when starting a new chat. Right now I accomplish this by copying `+page.svelte`, modifying that and then when I want to switch "profiles", I just copy the page to `web/src/routes/` and then restart the container. This is a bit clumsy and tedious. A way of doing this from the UI would be really helpful.

**Comment by nsarrazin** [comment]
I think that would be quite handy. In the short term, you can use the "new" button at the top of a chat to create a new chat with the same parameter as the current chat.

**Comment by agronholm** [comment]
What is also problematic is that the initial prompt is not visible anywhere. Perhaps that warrants a new issue?

**Comment by agronholm** [comment]
Oh, sorry! Indeed it was visible after updating. Thanks!
