### ISSUE TITLE
Integrate with langchain-serve?

### ISSUE THREAD

**Issue by deepankarm** [serge-chat/serge#228]
Hey, nice work with serge. Would you be open to integrating `serge` with [langchain-serve](https://github.com/jina-ai/langchain-serve)? This would mean, 

- You won't have to handle API routes yourself (we use FastAPI & Jina to handle/scale the routes).
- Can enable streaming using WebSocket & human-in-the-loop integration - this is a great addition for chat scenarios.
- Local to cloud-ready in just one command - `lc-serve deploy local/jcloud <app>` 
- Serverless/autoscaling endpoints with automatic tls certs on Cloud.

I understand serge is not integrated with langchain yet, but langchain-serve can deploy even on projects that don't work with langchain. (We just have websocket-based callback handlers explicitly built for langchain). 

Disclaimer: I'm the primary author of langchain-serve. Would be happy to collaborate on this!

**Comment by gaby** [comment]
@deepankarm I was looking into this but i'm a bit lost on how to use it only for local deployments.

**Comment by gaby** [comment]
Closing this, langchain-server has been archived.

https://github.com/jina-ai/langchain-serve/commit/22ce7ca86509635d0247a6f6a5b83546a6b8ef9b
