### ISSUE TITLE
Response not complete

### ISSUE THREAD

**Issue by sbendhiba** [serge-chat/serge#361]
### Bug description

After the latest release (0.1.3), I'm facing an issue with models not generating complete text.
I have tested multiple models (6), and it seems the issue is in the rendering of results (my guess).

### Steps to reproduce

New chat with any model.
ask for a result that would be formatted as code (example: can you generate a dockerfile based on debian 11 slim with apache2 using php 7.4 and composer?)
response incomplete "Sure, here’<|prompter|>s your DockerFile!" (see screenshot)

### Environment Information

Serge version: 0.1.3
Docker version: Docker version 20.10.21, build baeda1f
OS: Unraid Version: 6.11.5
CPU: Xeon E5-2698V3
Model: OAsst-LLaMA-30B
Model parameters: see screenshot

### Screenshots

Issue:
![image](https://github.com/nsarrazin/serge/assets/19827727/ca31ce41-a8f7-4227-879c-394e72b33a64)

Model setings:
![image](https://github.com/nsarrazin/serge/assets/19827727/2b703bc5-f2a7-4472-9fc4-40a0e3e54285)

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@sbendhiba Are you running the latest or main tag?

Can you try with a smaller model instead of the 30B one?

**Comment by kdubba** [comment]
I also faced this problem with Vicuna 7B. But increasing the max generated text length with Vicuna 13B solved the problem.

**Comment by sbendhiba** [comment]
@gaby Thank you for your response, I'm using the latest tag.
I think it related to the Maximum generated text length in tokens
because now I have an explicit message "Requested tokens exceed context window of 512"
is there any way to bypass this limit?

**Comment by Betanu701** [comment]
So interesting enough, I kinda glitched one of my models. It stopped the response after the default length was hit. Then I asked it a question, it responded. Then I gave it a command just to see what it would say. It then proceeded to continue the story from where it left off (actually backing up a couple words to start at the beginning of the sentence)

All settings default: except n_threads = 8 and no pre-prompt,
model: guanaco-7B-Q8_0

![convo_1](https://github.com/serge-chat/serge/assets/5798012/1a052719-281a-4f97-a3da-ad04fc29feb8)
![convo_2](https://github.com/serge-chat/serge/assets/5798012/65774b83-1619-40c5-bb92-90e9c462ff96)
![convo_3](https://github.com/serge-chat/serge/assets/5798012/1098bb8e-1ee5-41a3-9c92-8fe68e1ca1e5)

**Comment by ovizii** [comment]
> You need to add more than `512` on `prompt context length` the limit right now is `2048`

That didn't really help me either. See this discussion: https://github.com/serge-chat/serge/discussions/127#discussioncomment-6221436
