### ISSUE TITLE
Suggestion: Add minimum required RAM to /api/model/all and to GUI site "Download a model"

### ISSUE THREAD

**Issue by security-companion** [serge-chat/serge#365]
Hi,
I saw that in the readme it is included how much minimum RAM is required for each model but in the application itself in the GUI site "Download a model" this is not visible.
I would like to suggest to add a hint about the minimum required RAM in the API and the GUI, eg. behind the note about the size:
![grafik](https://github.com/nsarrazin/serge/assets/11234621/78cfd4e7-9e60-40ee-ae5f-542b1a9c3ac9)

What do you think?
Would you merge if I create a pull request?
Greetings

**Comment by fishscene** [comment]
I personally love the idea. 

Is there a way to do this programmatically so dev’s don’t have to manually populate this for every model? This has implications for allowing folks to add their own models in the future (but I don’t know if that’s on the roadmap).

Also would suggest making it obvious the type of RAM it is referring to, like:
4GB System RAM
… in the future, I’d like to see the ability to use GPU models, which would be designated as using “4GB VRAM”. Or something like that.

…just some thoughts!

**Comment by mzen17** [comment]
I'm thinking that someone can check the model by the type, i.e. 7B q2, q4, etc, and then use the table in the README at the main branch to automatically determine the amount of RAM.

**Comment by gaby** [comment]
I tried doing this but there's so many different models, 3B, 7B, 13B, 20B, 30B, 65B, 70B, etc etc.

**Comment by Smartappli** [comment]
Adapt model.json. I will

**Comment by gaby** [comment]
> Adapt model.json. I will

That's not the problem. Having to adapt each model added is extra development overhead not needed.

**Comment by gaby** [comment]
Closing as won't fix unless some library has a way to calculate this.

The table we had in the readme was invalid.
