### ISSUE TITLE
Support for k-quants new models with llama-cpp-python

### ISSUE THREAD

**Issue by pabl-o-ce** [serge-chat/serge#392]
[k-quants](https://github.com/ggerganov/llama.cpp/pull/1684) are a new improvement in ggml models. 

Using `llama-cpp-python` need to be able to support. For what I read for now you have to compile `llama-cpp-python` from source to support it.

I create this issue to be able to track whenever Serge can support k-quants in the future.

> So K_S is better accuracy, same file size, fractionally slower at 7B,  slower at 13B
K_M is much better accuracy, about 7% larger, fractionally quicker at 7B, same speed at 13B
~TheBloke

**Comment by gaby** [comment]
@pabl-o-ce I will bump llama-cpp-python to 159 today, which supports this.

**Comment by pabl-o-ce** [comment]
I can test it?
omg
