### ISSUE TITLE
Github codespaces

### ISSUE THREAD

**Issue by security-companion** [serge-chat/serge#439]
Hi,
I've been wondering if it might be a good idea to add github codespaces to this project.
This would enable us to quickly set up a dev environment and if everybody has the same dev environment it is easier to track down problems.
What do you think?
Greetings
security-companion

**Comment by nsarrazin** [comment]
Yeah I think it would be quite nice! But I've never set up something like this before, do you have any pointers ?

**Comment by security-companion** [comment]
Okay thanks for your comment.
Perhaps the following link might help. It's for flask but might be similar.
https://github.com/github/codespaces-flask/blob/main/.devcontainer/devcontainer.json

**Comment by gaby** [comment]
Closing this, PR's are welcome
