### ISSUE TITLE
Do you plan to support LoRa models?

### ISSUE THREAD

**Issue by qn1213** [serge-chat/serge#44]
https://github.com/Beomi/KoAlpaca
I loaded that model to use it, but I get an error.

>root@4bcef8bd0b49:/usr/src/app# llama -m weights/koAlpaca_65B.bin
>main: seed = 1679636956
>llama_model_load: loading model from 'weights/koAlpaca_65B.bin' - please wait ...
>llama_model_load: invalid model file 'weights/koAlpaca_65B.bin' (bad magic)
>llama_init_from_file: failed to load model

**Comment by gaby** [comment]
We are moving to GGUF models in the future.
