### ISSUE TITLE
Add a responsive design for mobile

### ISSUE THREAD

**Issue by Wgelyjr** [serge-chat/serge#47]
- Chat bar is doesn't block the chat window, so messages will be occluded by it
 - No hamburger icon to display menu
 - Chats don't occupy all of the width they could on the screen
 
 Great work. I'm super impressed by this project!

**Comment by nsarrazin** [comment]
Would be good to indeed add a responsive design for mobile. I'm pinning this issue so I don't forget about it :laughing:

**Comment by gaby** [comment]
Fixed via https://github.com/serge-chat/serge/pull/707
