### ISSUE TITLE
Kubernetes Helm Charts for serge.chat

### ISSUE THREAD

**Issue by mms-gianni** [serge-chat/serge#491]
Hey @gaby and @nsarrazin 

We've created some Helm charts for Serge to run it on a Kubernetes cluster.

Are you interested in moving it into your organization? 

https://github.com/mmz-srf/helm-serge

**Comment by gaby** [comment]
@mms-gianni Would it be possible to add them to this same repo? We can then deploy them as an artifact using github-actions

**Comment by mms-gianni** [comment]
Yes, I think so. I'll open a PR.

**Comment by gaby** [comment]
Thanks!

**Comment by gaby** [comment]
Closed via #500
