### ISSUE TITLE
Cant edit the front end

### ISSUE THREAD

**Issue by colouredflower** [serge-chat/serge#520]
### Bug description

cant update the ui, (the web version)

### Steps to reproduce

Simply run with docker, change settings in the app folder and run it

### Environment Information

Docker version 24.0.0, build 98fdcd7

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by Hardikanand1st** [comment]
Same
