### ISSUE TITLE
Responses to API questions place the full API output in chat

### ISSUE THREAD

**Issue by DarrylAnderson1** [serge-chat/serge#573]
### Bug description

When prompting via the API using post /chat/{chat_id}/question the full output from the API is reproduced in the web UI chat. This behavior can taint future responses causing the 'text' output to contain a full API-like response.

### Steps to reproduce

Submit a prompt via API using post /chat/{chat_id}/question
View the chat in the Serge web UI

### Environment Information

Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3

### Screenshots

Screenshots showing the same chat sequence with tainted output from the web UI and Mattermost
![image](https://github.com/serge-chat/serge/assets/122388237/769ec645-c98a-4afa-841a-f3f2dd83d8bc)
![image](https://github.com/serge-chat/serge/assets/122388237/16362222-cc2b-47c0-9fa8-8a6434945508)

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@DarrylAnderson1 Interesting bug, thanks for reporting. I will take a look during the week
