### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ykhaled** [serge-chat/serge#625]
### Bug description

sudo docker logs a5069b48c539
Collecting llama-cpp-python==0.1.66
  Downloading llama_cpp_python-0.1.66.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 10.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python==0.1.66) (4.7.1)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python==0.1.66) (1.25.1)
Collecting diskcache>=5.6.1 (from llama-cpp-python==0.1.66)
  Downloading diskcache-5.6.1-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 6.3 MB/s eta 0:00:00
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml): started
  Building wheel for llama-cpp-python (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [136 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      Not searching for unused variables given on the command line.

      -- The C compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.5s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f/_skbuild/linux-x86_64-3.11/cmake-build
        Command:
          /tmp/pip-build-env-0v1zmclx/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-0v1zmclx/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-0v1zmclx/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/local/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DPYTHON_LIBRARY:PATH=/usr/local/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/usr/local/bin/python -DPython_ROOT_DIR:PATH=/usr/local -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DPython3_EXECUTABLE:PATH=/usr/local/bin/python -DPython3_ROOT_DIR:PATH=/usr/local -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-0v1zmclx/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 10.2.1
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.5s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f/_skbuild/linux-x86_64-3.11/cmake-build
      [1/2] Generating /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f/vendor/llama.cpp/libllama.so
      FAILED: /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f/vendor/llama.cpp/libllama.so
      cd /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f/vendor/llama.cpp && make libllama.so
      I llama.cpp build info:
      I UNAME_S:  Linux
      I UNAME_P:  unknown
      I UNAME_M:  x86_64
      I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I LDFLAGS:
      I CC:       cc (Debian 10.2.1-6) 10.2.1 20210110
      I CXX:      g++ (Debian 10.2.1-6) 10.2.1 20210110

      g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -c llama.cpp -o llama.o
      cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS   -c ggml.c -o ggml.o
      In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:111,
                       from ggml.c:249:
      ggml.c: In function ‘ggml_vec_dot_q4_0_q8_0’:
      /usr/lib/gcc/x86_64-linux-gnu/10/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
         63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
            | ^~~~~~~~~~~~~~~
      ggml.c:2397:15: note: called from here
       2397 |         acc = _mm256_fmadd_ps( d, q, acc );
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:111,
                       from ggml.c:249:
      /usr/lib/gcc/x86_64-linux-gnu/10/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
         63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
            | ^~~~~~~~~~~~~~~
      ggml.c:2397:15: note: called from here
       2397 |         acc = _mm256_fmadd_ps( d, q, acc );
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:111,
                       from ggml.c:249:
      /usr/lib/gcc/x86_64-linux-gnu/10/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
         63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
            | ^~~~~~~~~~~~~~~
      ggml.c:2397:15: note: called from here
       2397 |         acc = _mm256_fmadd_ps( d, q, acc );
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:111,
                       from ggml.c:249:
      /usr/lib/gcc/x86_64-linux-gnu/10/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
         63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
            | ^~~~~~~~~~~~~~~
      ggml.c:2397:15: note: called from here
       2397 |         acc = _mm256_fmadd_ps( d, q, acc );
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      make: *** [Makefile:256: ggml.o] Error 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-0v1zmclx/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-0v1zmclx/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-0v1zmclx/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-0v1zmclx/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f
        Working directory:
          /tmp/pip-install-7csvtwj7/llama-cpp-python_927e9a995c4c4affb026e292f727b10f/_skbuild/linux-x86_64-3.11/cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
Collecting llama-cpp-python==0.1.66
  Using cached llama_cpp_python-0.1.66.tar.gz (1.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python==0.1.66) (4.7.1)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python==0.1.66) (1.25.1)
Collecting diskcache>=5.6.1 (from llama-cpp-python==0.1.66)
  Using cached diskcache-5.6.1-py3-none-any.whl (45 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml): started
  Building wheel for llama-cpp-python (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [136 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      Not searching for unused variables given on the command line.

      -- The C compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.5s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37/_skbuild/linux-x86_64-3.11/cmake-build
        Command:
          /tmp/pip-build-env-918t8jvp/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-918t8jvp/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-918t8jvp/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/local/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DPYTHON_LIBRARY:PATH=/usr/local/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/usr/local/bin/python -DPython_ROOT_DIR:PATH=/usr/local -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DPython3_EXECUTABLE:PATH=/usr/local/bin/python -DPython3_ROOT_DIR:PATH=/usr/local -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/local/include/python3.11 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-918t8jvp/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 10.2.1
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37/_skbuild/linux-x86_64-3.11/cmake-build
      [1/2] Generating /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37/vendor/llama.cpp/libllama.so
      FAILED: /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37/vendor/llama.cpp/libllama.so
      cd /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37/vendor/llama.cpp && make libllama.so
      I llama.cpp build info:
      I UNAME_S:  Linux
      I UNAME_P:  unknown
      I UNAME_M:  x86_64
      I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I LDFLAGS:
      I CC:       cc (Debian 10.2.1-6) 10.2.1 20210110
      I CXX:      g++ (Debian 10.2.1-6) 10.2.1 20210110

      g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -c llama.cpp -o llama.o
      cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS   -c ggml.c -o ggml.o
      In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:111,
                       from ggml.c:249:
      ggml.c: In function ‘ggml_vec_dot_q4_0_q8_0’:
      /usr/lib/gcc/x86_64-linux-gnu/10/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
         63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
            | ^~~~~~~~~~~~~~~
      ggml.c:2397:15: note: called from here
       2397 |         acc = _mm256_fmadd_ps( d, q, acc );
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:111,
                       from ggml.c:249:
      /usr/lib/gcc/x86_64-linux-gnu/10/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
         63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
            | ^~~~~~~~~~~~~~~
      ggml.c:2397:15: note: called from here
       2397 |         acc = _mm256_fmadd_ps( d, q, acc );
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:111,
                       from ggml.c:249:
      /usr/lib/gcc/x86_64-linux-gnu/10/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
         63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
            | ^~~~~~~~~~~~~~~
      ggml.c:2397:15: note: called from here
       2397 |         acc = _mm256_fmadd_ps( d, q, acc );
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:111,
                       from ggml.c:249:
      /usr/lib/gcc/x86_64-linux-gnu/10/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
         63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
            | ^~~~~~~~~~~~~~~
      ggml.c:2397:15: note: called from here
       2397 |         acc = _mm256_fmadd_ps( d, q, acc );
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      make: *** [Makefile:256: ggml.o] Error 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-918t8jvp/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-918t8jvp/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-918t8jvp/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-918t8jvp/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37
        Working directory:
          /tmp/pip-install-jdol6e3n/llama-cpp-python_2576981833ec4f1181c201fc4e7ecc37/_skbuild/linux-x86_64-3.11/cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

### Steps to reproduce

git clone https://github.com/nsarrazin/serge.git && cd serge
docker compose up -d

### Environment Information

Docker version 20.10.24, build 297e128

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by ykhaled** [comment]
I have VBOX (Oracle):
 sudo lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
    CPU family:          6
    Model:               85
    Thread(s) per core:  1
    Core(s) per socket:  16
    Socket(s):           1
    Stepping:            4
    BogoMIPS:            4190.15
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_t
                         sc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsav
                         e avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   512 KiB (16 instances)
  L1i:                   512 KiB (16 instances)
  L2:                    16 MiB (16 instances)
  L3:                    176 MiB (16 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-15
Vulnerabilities:
  Itlb multihit:         KVM: Mitigation: VMX unsupported
  L1tf:                  Mitigation; PTE Inversion
  Mds:                   Mitigation; Clear CPU buffers; SMT Host state unknown
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Mitigation; Clear CPU buffers; SMT Host state unknown
  Retbleed:              Vulnerable
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected

**Comment by mzen17** [comment]
Did you enable the AVX on the VM? If you don't, even if the host has AVX, the VM won't.

**Comment by ykhaled** [comment]
Thank for the prompt reply.
I have many complex guest VMs operating on this host.
Anyway - these are my settings:
![image](https://github.com/serge-chat/serge/assets/16475289/6a73f631-a560-4468-aa77-4f965e47ce5a)

**Comment by ykhaled** [comment]
I switched from Virtual Box to VM-Ware and that seems to resolve the issue for me.
