### ISSUE TITLE
Feature: Add user accounts to support multiple users on a single node.

### ISSUE THREAD

**Issue by mzen17** [serge-chat/serge#632]
If multiple users are using the chat, they share the same chat pool and the same account, where everyone can use it and post to each other's chats. 

It should be made that chat messages are tied to a certain user, and the frontend's request to the server asking for the chats should specify which user it is getting chat messages for.

**Comment by gaby** [comment]
I thought about doing this using [Pocketbase.io](https://pocketbase.io) still havent seat down to start looking into it.

Some part of the backend need a rewrite before adding any major changes.

**Comment by gaby** [comment]
Closing in favor of #950
