### ISSUE TITLE
Where is the LLM stored

### ISSUE THREAD

**Issue by stumueller** [serge-chat/serge#648]
### Bug description

Where is the LLM downloaded to? I presume it is stored in the docker image?
If not would I have to re-download the LLM each time I start the docker image?

### Steps to reproduce

none

### Environment Information

WSL2

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
Hello @stumueller if you used the following to run your container:

```console
docker run -d \
    --name serge \
    -v weights:/usr/src/app/weights \
    -v datadb:/data/db/ \
    -p 8008:8008 \
    ghcr.io/serge-chat/serge:latest
```

The models are stored in `/usr/src/app/weights`, or in the `weights` volume that can be found by running `docker volume ls`.

You can also bind mount to make it easier to find, like this:

```console
mkdir -p /data/serge

docker run -d \
    --name serge \
    -v /data/serge/weights:/usr/src/app/weights \
    -v /data/serge/db:/data/db/ \
    -p 8008:8008 \
    ghcr.io/serge-chat/serge:latest
```
