### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by JuniperChris929** [serge-chat/serge#652]
### Bug description

When running this Docker container with IPv6 only the UI (web) never shows up :(

### Steps to reproduce

Spin up the Docker container with just a connection to an IPv6-only network

### Environment Information

-

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
Yeah it defaults to ipv6, i will fix this

**Comment by JuniperChris929** [comment]
As a quick "hack" I changed the host-part inside deploy.sh from 0.0.0.0 to :: - making it v6 only now. Unsure if this is the only place where I have to do this but it seems to work. Maybe there's even a trick to tell it to use both IPv4 and IPv6 :) Thanks for your fast reply 👍🏻
