### ISSUE TITLE
🐛 [Bug]: Minotaur-15B model stuck at download and does not run

### ISSUE THREAD

**Issue by CorentinWicht** [serge-chat/serge#701]
### Bug description

Dear Serge Team,

I tried to install the `Minotaur-15B` model from the UI and it got stuck twice between 92.5 and 93.5%, then I tried to refresh the page (as suggested in #111) and the UI indicated that it was actually installed. Switching back to the home page, I tried to press the [START A NEW CHAT] button nothing happened:
![image](https://github.com/serge-chat/serge/assets/52161904/278111c6-272a-4261-9501-55d95c31b1b4)

Strangely, I realized that if I refresh the list of downloadable models, `Minotaur-15B` disappears (as well as others) while the `Facebook-LLaMA2` appear. 
I see that `Minotaur-15B` has been introduced since release 0.3.0, does this mean that it's not supported anymore? 

Weirdly enough there is a mismatch between the list of supported models in `model.json` in:
a) The [default refresh URL](https://raw.githubusercontent.com/serge-chat/serge/main/api/src/serge/data/models.json) provided in the UI
b) The file (serge-0.3.2/api/src/serge/data/models.json) provided in the 0.3.2 zip archive.
c) The file in the main branch of the [github repo](https://github.com/serge-chat/serge/blob/main/api/src/serge/data/models.json).

Thus, I am unsure which `model.json` file contains the models that are actually working? 
Is the list in the [README.md fil](https://github.com/serge-chat/serge/blob/main/api/src/serge/data/models.json)e the only one that is reliable? 

### Steps to reproduce

1. Download latest release ([0.3.2](https://github.com/serge-chat/serge/releases/tag/0.3.2))
2. In Windows, open CMD and run `wsl`, go to the 0.3.2 release directory and run the "[Quick Start](https://github.com/serge-chat/serge/releases/tag/0.3.2)" docker commands
3. go to [http://localhost:8008/](http://localhost:8008/), click on [Download Models]: Model `Minotaur-15B` appears in the list while `Facebook-LLaMA2` are missing.
4. Pressing on [Refresh models], then [Refresh] using [default URL](https://raw.githubusercontent.com/serge-chat/serge/main/api/src/serge/data/models.json).
5. `Facebook-LLaMA2` models (7B-13B-70B) appear while `Minotaur-15B` disappears.

### Environment Information

Docker version 24.0.5, build ced0996
Microsoft Windows 10 Enterprise 10.0.19044
WSL 2 - Ubuntu 22.04.3 LTS

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@CorentinWicht The list on the readme is the one from `main`. If you are using latest or a tagged release that may be why of the mismatch.

I plan on doing a release, but there's some bugs that need to be fixed first.

Try using the `main` tag, and see if the problem persists

**Comment by CorentinWicht** [comment]
> @CorentinWicht The list on the readme is the one from `main`. If you are using latest or a tagged release that may be why of the mismatch.
> 
> I plan on doing a release, but there's some bugs that need to be fixed first.
> 
> Try using the `main` tag, and see if the problem persists

Very good, thanks for your prompt reply.
But why where models like `Minotaur-15B` introduced in v.0.3.0 and removed right away? #541 

Any chance a model like [TheBloke/starcoderplus-GGML](https://huggingface.co/TheBloke/starcoderplus-GGML) be supported in upcoming releases?

**Comment by pabl-o-ce** [comment]
@gaby yes this are GPT2 architecture models so `python-llama-cpp` only work exclusively for GGML and now GGUF (it was my mistake to added)
