### ISSUE TITLE
No models running at all

### ISSUE THREAD

**Issue by C-Nubela** [serge-chat/serge#734]
### Serge not running

Hi, after installing Serge on Docker Compose, running it, and installing a couple of models; none of them run.

It just sits there with three dots and never responds. Any idea why?

### Checklist:

- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
Hello@C-Nubela can you open this as a bug report, we can't help without logs and more details.
