### ISSUE TITLE
🚀 [Feature]: add vigogne and  Marx-3B models

### ISSUE THREAD

**Issue by Arthur-Llevelys** [serge-chat/serge#736]
### Feature Description

Could you add theses 2 models : 
Serge: Marx-3B-V2-Q4_1-GGML : 
GGML: https://huggingface.co/NikolayKozloff/Marx-3B-V2/resolve/main/Marx-3B-V2-Q4_1-GGML.bin
GGUF: https://huggingface.co/NikolayKozloff/Marx-3B-V2-GGUF/resolve/main/Marx-3B-V2-Q4_1-GGUF.gguf
and vigogne for french : 
https://huggingface.co/TheBloke/Vigogne-2-13B-Instruct-GGML/tree/main
https://huggingface.co/TheBloke/Vigogne-2-7B-Instruct-GGML/tree/main
https://huggingface.co/TheBloke/Vigogne-2-7B-Chat-GGML/tree/main

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
@Arthur-Llevelys GGML models are deprecated, do they have GGUF?

**Comment by Arthur-Llevelys** [comment]
I think so...
https://huggingface.co/TheBloke/Vigogne-2-13B-Instruct-GGUF
https://huggingface.co/TheBloke/Vigogne-2-7B-Chat-GGML/blob/main/LICENSE.txt

**Comment by k0gen** [comment]
I have tested Marx and it is a very capable small model.
I'll add it

**Comment by gaby** [comment]
Fixed via #738
