### ISSUE TITLE
🤗 [Question]: Is there an easy way to pass a prompt in a URL and get the answer returned?

### ISSUE THREAD

**Issue by anethema** [serge-chat/serge#781]
### Question Description

I want to make Serge work with a discord bot. Is there an easy way to pass a prompt through a URL and get the answer returned? I want to self host a LLM and have the users able to pass prompts and have the bot reply. 

### Checklist:

- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@anethema Join the discord, someone is already doing this and can help you there.
