### ISSUE TITLE
Add support for Light theme to the chat interface

### ISSUE THREAD

**Issue by paraskevasleivadaros** [serge-chat/serge#80]
As a user of the chat interface, I find the current Dark theme to be visually appealing and easy on the eyes. However, I would also like to have the option to switch to a Light theme for the interface, especially when using the app in a well-lit environment.

**Comment by huksley** [comment]
@paraskevasleivadaros Pull request would be appreciated, if you want to start, check out https://github.com/nsarrazin/serge/blob/main/web/src/app.html and https://tailwindcss.com/docs/dark-mode

**Comment by nsarrazin** [comment]
We use Daisy UI which has its own themes feel free to have a look at their
theme solution !

**Comment by gaby** [comment]
@paraskevasleivadaros I spent over 2hrs trying to use the official solution from daisyui, and can't get the themes to change.
