### ISSUE TITLE
🐛 [Bug]: So insanely slow, even on high CPU and RAM settings.

### ISSUE THREAD

**Issue by Mrs-Feathers** [serge-chat/serge#842]
### Bug description

Runs super slow in docker on proxmox lxc. even with 6 cores, 50gb ram (running proxmox on an hp prolient dl380 G7) and the smallest 7B still takes about 15 minutes before it even shows up.

### Steps to reproduce

1. use the docker code in a proxmox lxc
2. download any AI core
3. try to talk to it

### Environment Information

docker: Docker version 24.0.2, build cb74dfc
OS: Linux
OS Version: Debian 11
Server Model: HP Proliant DL380 G7

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@Mrs-Feathers Can you run the following command `cat /proc/cpuinfo | grep -i avx`

I think you need to change the CPU settings for the VM, by default they don't get all the features of the host. Without `avx` ai models are super slow

**Comment by gaby** [comment]
See here https://forum.proxmox.com/threads/avx2-and-avx-flags-on-vm.87808/ you have to change the cpu in advance features of the guest to `host`.
