### ISSUE TITLE
🐛 [Bug]: CodeLlama-7B instruct download stuck

### ISSUE THREAD

**Issue by BingChillz** [serge-chat/serge#910]
### Bug description

CodeLlama-7B instruct download stuck at 93.4%. I am able to use the model though. This doesn't happen with other models like Mistral-7B-OpenOrca.

### Steps to reproduce

Download CodeLlama-7B-model

### Environment Information

Docker version 24.0.7, build afdd53b

### Screenshots

![image](https://github.com/serge-chat/serge/assets/146423397/a991a79f-6da9-4e58-9835-19a176cbd3c3)

### Relevant log output

```shell
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
INFO:     192.168.29.143:50268 - "GET /model/CodeLlama-7B-Instruct/download/status HTTP/1.1" 200 OK
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@BingChillz Thanks for the report, we had someone else report the same issue on Discord. I'm investigating.

**Comment by Normand-Nadon** [comment]
I have the same issue with all 13B models

They seem to download LLaMA2-13B + the model I want and both are stuck at 99%
![image](https://github.com/serge-chat/serge/assets/60982016/9c34a54b-669d-40ba-ae3c-fe8f5f70b7f0)

![image](https://github.com/serge-chat/serge/assets/60982016/fa9f0975-dd41-4a47-aad7-11f287adcfd5)

**Comment by gaby** [comment]
I can't seem to be able to replicate this issue. Are you running a brand new Serge installation?

**Comment by gaby** [comment]
Found the issue, the size in the `models.json` doesn't match the size of the File on HuggingFace

**Comment by gaby** [comment]
@Normand-Nadon I will fix it on my side, fix will be available sometime this week with the next release.

**Comment by Normand-Nadon** [comment]
Amazing! That is why the FOSS community is the best!
