### ISSUE TITLE
🤗 [Question]: I cannot use a custom model

### ISSUE THREAD

**Issue by a55664967s** [serge-chat/serge#916]
### Question Description

I downloaded a Chinese model, but there is no response after clicking 'Start a new chat.
I based this article on https://ivonblog.com/posts/serge-ai-installation/
![1](https://github.com/serge-chat/serge/assets/56185422/681f4f14-ccb9-45a0-bc3a-8221b9d70649)
![2](https://github.com/serge-chat/serge/assets/56185422/69b0fea7-f65b-4a4a-a2d1-65ed4a219431)
![3](https://github.com/serge-chat/serge/assets/56185422/d294173c-5ef4-4c41-ba45-ac704f3e215a)

### Checklist:

- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@a55664967s You have to use the `GGUF` model. Looking at the logs you are using the `GGML` which are deprecated.

**Comment by a55664967s** [comment]
> @a55664967s You have to use the `GGUF` model. Looking at the logs you are using the `GGML` which are deprecated.

Thanks for your answer, I'll try it
