### ISSUE TITLE
how to use  mixtral-8x7b-v0.1🤗 [Question]: 

### ISSUE THREAD

**Issue by osnapitsjoey** [serge-chat/serge#984]
### Question Description

ive downloaded the gguf because thats the format the other files are in, yet it doesnt show up. so i renamed it to .bin and it shows up but dont not run. it says its supported in this app, i think im just doing something wrong

### Checklist:

- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@osnapitsjoey I'm doing a release tonight. It requires updating some dependencies. There's over 60 commits since the last release.

I will tag you again once release is ready.

**Comment by gaby** [comment]
@osnapitsjoey Fixed via https://github.com/serge-chat/serge/releases/tag/0.8.0

Download the `latest` tag of the docker image.

```bash
docker pull ghcr.io/serge-chat/serge:latest
```
